'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Shell } from '../../../components/Shell';
import { generateOverview, getOverview, type SourceOverview, type Certainty } from '../../../../lib/api';

const CERTAINTY_COLOR: Record<Certainty, string> = {
  confirmed: '#16a34a',
  strong_inference: '#2563eb',
  weak_assumption: '#d97706',
  needs_confirmation: '#dc2626',
};

function CertaintyBadge({ certainty }: { certainty: Certainty }) {
  return (
    <span
      className="badge"
      style={{ background: `${CERTAINTY_COLOR[certainty]}22`, color: CERTAINTY_COLOR[certainty] }}
    >
      {certainty.replace(/_/g, ' ')}
    </span>
  );
}

export default function OverviewPage({ params }: { params: { id: string } }) {
  const { id } = params;
  const [overview, setOverview] = useState<SourceOverview | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    getOverview(id)
      .then(setOverview)
      .catch((e) => setError(e.message));
  }, [id]);

  async function regenerate() {
    setBusy(true);
    try {
      setOverview(await generateOverview(id));
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <Shell
      title="AI source understanding"
      subtitle="Evidence-backed. Every conclusion is tagged with a certainty — confirmed facts are separated from inference and weak assumptions."
    >
      <div style={{ display: 'flex', gap: 10, marginBottom: 18 }}>
        <Link className="btn" style={{ background: 'var(--color-muted)' }} href={`/schemas/${id}`}>
          ← Back to schema
        </Link>
        <button className="btn" onClick={regenerate} disabled={busy}>
          {busy ? 'Regenerating…' : 'Regenerate'}
        </button>
      </div>
      {error && <p className="error">{error}</p>}
      {overview && (
        <>
          <p className="subtle" style={{ fontSize: 13 }}>Generated by: <strong>{overview.generatedBy}</strong></p>

          <div className="grid" style={{ gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))' }}>
            {overview.tables.map((t) => (
              <div className="card" key={t.entityRef}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                  <h3 style={{ margin: 0 }}>{t.likelyEntity}</h3>
                  <span className="badge">{t.classification}</span>
                </div>
                <p className="subtle" style={{ fontSize: 13, marginTop: 6 }}>{t.likelyPurpose}</p>
                <div style={{ margin: '8px 0' }}>
                  <CertaintyBadge certainty={t.certainty} />
                  {t.needsUserConfirmation && (
                    <span className="badge" style={{ background: '#fde68a55', color: '#92400e' }}>confirm</span>
                  )}
                </div>
                {t.importantFields.length > 0 && (
                  <p style={{ fontSize: 13, margin: '4px 0' }}>
                    <strong>Key fields:</strong> {t.importantFields.join(', ')}
                  </p>
                )}
                <details>
                  <summary className="subtle" style={{ fontSize: 12, cursor: 'pointer' }}>
                    Evidence ({t.evidence.length})
                  </summary>
                  <ul style={{ fontSize: 12, color: 'var(--color-muted)', margin: '6px 0', paddingLeft: 18 }}>
                    {t.evidence.map((e, i) => (
                      <li key={i}>
                        <em>{e.kind}</em>: {e.detail}
                      </li>
                    ))}
                  </ul>
                </details>
              </div>
            ))}
          </div>

          {overview.suggestedJoinPaths.length > 0 && (
            <div className="card" style={{ marginTop: 18 }}>
              <h3 style={{ marginTop: 0 }}>Suggested join paths</h3>
              {overview.suggestedJoinPaths.map((j, i) => (
                <div key={i} style={{ fontSize: 13, padding: '3px 0' }}>
                  <code>{j.from} → {j.to}</code> <span className="subtle">via {j.via}</span>{' '}
                  <CertaintyBadge certainty={j.certainty} />
                </div>
              ))}
            </div>
          )}

          {overview.areasRequiringConfirmation.length > 0 && (
            <div className="card" style={{ marginTop: 18, borderColor: '#fca5a5' }}>
              <h3 style={{ marginTop: 0 }}>Areas requiring human confirmation</h3>
              <ul style={{ margin: 0, paddingLeft: 18, fontSize: 13 }}>
                {overview.areasRequiringConfirmation.map((a, i) => (
                  <li key={i}>{a}</li>
                ))}
              </ul>
            </div>
          )}
        </>
      )}
    </Shell>
  );
}
