'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Shell } from '../../../components/Shell';
import { ProjectTabs } from '../../../components/ProjectTabs';
import {
  getProject,
  listSchemas,
  listSuggestions,
  sendMappingFeedback,
  suggestMappings,
  type MappingSuggestion,
  type Project,
  type SchemaSummary,
} from '../../../../lib/api';

function ConfidenceBar({ value }: { value: number }) {
  const pct = Math.round(value * 100);
  const color = value >= 0.9 ? '#16a34a' : value >= 0.6 ? '#d97706' : '#dc2626';
  return (
    <div title={`${pct}%`} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
      <div style={{ width: 60, height: 6, background: 'var(--color-border)', borderRadius: 3 }}>
        <div style={{ width: `${pct}%`, height: 6, background: color, borderRadius: 3 }} />
      </div>
      <span style={{ fontSize: 12, color }}>{pct}%</span>
    </div>
  );
}

const statusColor: Record<string, string> = {
  proposed: 'var(--color-muted)',
  accepted: '#16a34a',
  rejected: '#dc2626',
  modified: '#2563eb',
};

export default function MappingWorkspace({ params }: { params: { id: string } }) {
  const projectId = params.id;
  const [project, setProject] = useState<Project | null>(null);
  const [schemas, setSchemas] = useState<SchemaSummary[]>([]);
  const [sourceId, setSourceId] = useState('');
  const [targetId, setTargetId] = useState('');
  const [suggestions, setSuggestions] = useState<MappingSuggestion[]>([]);
  const [unmapped, setUnmapped] = useState<string[]>([]);
  const [missing, setMissing] = useState<string[]>([]);
  const [generatedBy, setGeneratedBy] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    getProject(projectId).then(setProject).catch(() => undefined);
    listSchemas().then(setSchemas).catch((e) => setError(e.message));
    listSuggestions(projectId)
      .then((s) => {
        if (s.length) setSuggestions(s);
      })
      .catch(() => undefined);
  }, [projectId]);

  async function generate() {
    if (!sourceId || !targetId) return;
    setBusy(true);
    setError(null);
    try {
      const res = await suggestMappings(sourceId, targetId, projectId);
      setSuggestions(res.suggestions);
      setUnmapped(res.unmappedSources);
      setMissing(res.missingRequiredTargets);
      setGeneratedBy(res.generatedBy);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }

  async function decide(s: MappingSuggestion, decision: 'accepted' | 'rejected') {
    setSuggestions((prev) => prev.map((x) => (x.id === s.id ? { ...x, status: decision } : x)));
    try {
      await sendMappingFeedback(s.id, decision);
    } catch (e) {
      setError((e as Error).message);
    }
  }

  const accepted = suggestions.filter((s) => s.status === 'accepted').length;

  return (
    <Shell
      title="Mapping workspace"
      subtitle={project ? `${project.name} — review AI suggestions, then accept to promote them into deterministic draft config.` : undefined}
    >
      <ProjectTabs projectId={projectId} />
      <div className="card" style={{ marginBottom: 18 }}>
        <div style={{ display: 'flex', gap: 12, alignItems: 'flex-end', flexWrap: 'wrap' }}>
          <div className="field" style={{ margin: 0 }}>
            <label>Source schema</label>
            <select value={sourceId} onChange={(e) => setSourceId(e.target.value)} style={sel}>
              <option value="">Select…</option>
              {schemas.map((s) => (
                <option key={s.id} value={s.id}>{s.name}</option>
              ))}
            </select>
          </div>
          <div className="field" style={{ margin: 0 }}>
            <label>Target schema</label>
            <select value={targetId} onChange={(e) => setTargetId(e.target.value)} style={sel}>
              <option value="">Select…</option>
              {schemas.map((s) => (
                <option key={s.id} value={s.id}>{s.name}</option>
              ))}
            </select>
          </div>
          <button className="btn" onClick={generate} disabled={busy || !sourceId || !targetId}>
            {busy ? 'Generating…' : 'Generate AI mappings'}
          </button>
        </div>
        {schemas.length === 0 && (
          <p className="subtle" style={{ fontSize: 13 }}>
            No schemas yet — <Link href="/schemas">ingest source & target schemas</Link> first.
          </p>
        )}
        {generatedBy && <p className="subtle" style={{ fontSize: 13, margin: '10px 0 0' }}>Generated by: <strong>{generatedBy}</strong> · {accepted}/{suggestions.length} accepted</p>}
        {error && <p className="error">{error}</p>}
      </div>

      {suggestions.length > 0 && (
        <div className="card" style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
            <thead>
              <tr style={{ textAlign: 'left', color: 'var(--color-muted)' }}>
                <th style={th}>Source</th>
                <th style={th}>Target</th>
                <th style={th}>Type</th>
                <th style={th}>Confidence</th>
                <th style={th}>Reasoning & risks</th>
                <th style={th}>Decision</th>
              </tr>
            </thead>
            <tbody>
              {suggestions.map((s) => (
                <tr key={s.id} style={{ borderTop: '1px solid var(--color-border)' }}>
                  <td style={td}><code>{s.sourceField ?? '—'}</code></td>
                  <td style={td}><code>{s.targetField}</code></td>
                  <td style={td}><span className="badge">{s.mappingType}</span></td>
                  <td style={td}><ConfidenceBar value={s.confidence} /></td>
                  <td style={td}>
                    <div>{s.reasoning}</div>
                    {s.risks.map((r, i) => (
                      <div key={i} style={{ color: '#d97706', fontSize: 12 }}>⚠ {r}</div>
                    ))}
                    {s.evidence.length > 0 && (
                      <details>
                        <summary className="subtle" style={{ fontSize: 11, cursor: 'pointer' }}>evidence</summary>
                        <ul style={{ fontSize: 11, margin: '4px 0', paddingLeft: 16, color: 'var(--color-muted)' }}>
                          {s.evidence.map((e, i) => (
                            <li key={i}>{e.detail}</li>
                          ))}
                        </ul>
                      </details>
                    )}
                  </td>
                  <td style={td}>
                    {s.status === 'proposed' ? (
                      <div style={{ display: 'flex', gap: 6 }}>
                        <button style={miniBtn('#16a34a')} onClick={() => decide(s, 'accepted')}>Accept</button>
                        <button style={miniBtn('#dc2626')} onClick={() => decide(s, 'rejected')}>Reject</button>
                      </div>
                    ) : (
                      <span style={{ color: statusColor[s.status], fontWeight: 600 }}>{s.status}</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {(unmapped.length > 0 || missing.length > 0) && (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginTop: 18 }}>
          <div className="card">
            <h3 style={{ marginTop: 0 }}>Unmapped source fields ({unmapped.length})</h3>
            <div style={{ fontSize: 12, color: 'var(--color-muted)' }}>{unmapped.join(', ') || 'None'}</div>
          </div>
          <div className="card" style={{ borderColor: missing.length ? '#fca5a5' : undefined }}>
            <h3 style={{ marginTop: 0 }}>Missing required targets ({missing.length})</h3>
            <div style={{ fontSize: 12, color: missing.length ? '#dc2626' : 'var(--color-muted)' }}>
              {missing.join(', ') || 'None'}
            </div>
          </div>
        </div>
      )}
    </Shell>
  );
}

const sel: React.CSSProperties = {
  padding: '9px 12px',
  border: '1px solid var(--color-border)',
  borderRadius: 'var(--radius)',
  fontSize: 14,
  background: 'var(--color-surface)',
  minWidth: 200,
};
const th: React.CSSProperties = { padding: '6px 8px', fontWeight: 500 };
const td: React.CSSProperties = { padding: '8px', verticalAlign: 'top' };
const miniBtn = (bg: string): React.CSSProperties => ({
  background: bg,
  color: '#fff',
  border: 'none',
  borderRadius: 6,
  padding: '5px 10px',
  fontSize: 12,
  cursor: 'pointer',
});
